AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  UploadsNotificationFunction - A SAM template to handle SQS events and publish to SNS

Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    LoggingConfig:
      LogFormat: JSON # Ensures logs appear in JSON format.
    Architectures:
      - x86_64 # Specifies the architecture for the Lambda function.

Resources:
  # Lambda Function: UploadsNotificationHandler
  UploadsNotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.example.aws.lambda.UploadsNotificationHandler::handleRequest
      Runtime: java17
      CodeUri: HelloWorldFunction/target/sohit-UploadsNotificationFunction.jar
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - "sns:Publish"
              - "sqs:ReceiveMessage"
              - "sqs:DeleteMessage"
              - "sqs:GetQueueAttributes"
            Resource:
              - !GetAtt NotificationQueue.Arn
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt NotificationQueue.Arn

  # SQS Queue: NotificationQueue
  NotificationQueue:
    Type: AWS::SQS::Queue

  # SNS Topic: UploadsNotificationTopic
  UploadsNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Protocol: email
          Endpoint: your-email@example.com

  # Application Insights (Optional)
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'