version: 0.2

phases:
  install:
    runtime-versions:
      java: 17
    commands:
      - echo "Installing dependencies"
      - mvn install
  build:
    commands:
      - echo "Building JAR file with Maven"
      - mvn package
      - echo "Packaging SAM application"
      - sam package --template-file template.yaml --s3-bucket sohit-rajput-web --output-template-file packaged-template.yaml
artifacts:
  files:
    - packaged-template.yaml